insert into tb_uf (id_uf,sigla,nome) Values(12,'AC','Acre');  
insert into tb_uf (id_uf,sigla,nome) Values(27,'AL','Alagoas');  
insert into tb_uf (id_uf,sigla,nome) Values(13,'AM','Amazonas');
insert into tb_uf (id_uf,sigla,nome) Values(16,'AP','Amapá');
insert into tb_uf (id_uf,sigla,nome) Values(29,'BA','Bahia');
insert into tb_uf (id_uf,sigla,nome) Values(23,'CE','Ceará');
insert into tb_uf (id_uf,sigla,nome) Values(53,'DF','Distrito Federal');
insert into tb_uf (id_uf,sigla,nome) Values(32,'ES','Espírito Santo');
insert into tb_uf (id_uf,sigla,nome) Values(52,'GO','Goiás');
insert into tb_uf (id_uf,sigla,nome) Values(21,'MA','Maranhão');
insert into tb_uf (id_uf,sigla,nome) Values(31,'MG','Minas Gerais');
insert into tb_uf (id_uf,sigla,nome) Values(50,'MS','Mato Grosso do Sul');
insert into tb_uf (id_uf,sigla,nome) Values(51,'MT','Mato Grosso');
insert into tb_uf (id_uf,sigla,nome) Values(15,'PA','Pará');
insert into tb_uf (id_uf,sigla,nome) Values(25,'PB','Paraíba');
insert into tb_uf (id_uf,sigla,nome) Values(26,'PE','Pernambuco');
insert into tb_uf (id_uf,sigla,nome) Values(22,'PI','Piauí');
insert into tb_uf (id_uf,sigla,nome) Values(41,'PR','Paraná');
insert into tb_uf (id_uf,sigla,nome) Values(33,'RJ','Rio de Janeiro');
insert into tb_uf (id_uf,sigla,nome) Values(24,'RN','Rio Grande do Norte');
insert into tb_uf (id_uf,sigla,nome) Values(11,'RO','Rondônia');
insert into tb_uf (id_uf,sigla,nome) Values(14,'RR','Roraima');
insert into tb_uf (id_uf,sigla,nome) Values(43,'RS','Rio Grande do Sul');
insert into tb_uf (id_uf,sigla,nome) Values(42,'SC','Santa Catarina');
insert into tb_uf (id_uf,sigla,nome) Values(28,'SE','Sergipe');
insert into tb_uf (id_uf,sigla,nome) Values(35,'SP','São Paulo');
insert into tb_uf (id_uf,sigla,nome) Values(17,'TO','Tocantins');
